### PR TITLE
Add collection implode method

### PR DESCRIPTION
**Pull request by milous**
bug fix? no
new feature? yes
BC break? no

adds support for implode collection

### CODE REVIEW

**Comment by DusanKasan** [comment]
This is already implemented as http://dusankasan.github.io/Knapsack/#Operations-interpose

Is this what you need?

**Comment by issei-m** [comment]
@DusanKasan You mean `reduce`, don't you? That can completely do what @milous  want.

```php
$separator = ',';
$joined = Collection::from(['foo', 'bar', 'piyo'])
    ->reduce(function ($acc, $v) use ($separator) { return $acc .= ($acc === '' ? '' : $separator) . $v; }, '')
;
var_dump($joined); // string(12) "foo,bar,piyo"
```

**Comment by DusanKasan** [comment]
Well yeah that also but interpose + toString might be more readable :) either way you can achieve this functionality by composing existing operators.

**Comment by milous** [comment]
My usecase
```php
// echo \implode(', ', $collection->toArray());
echo \implode(', ', $collection->values()->toArray());
```
and I think
```php
echo $collection->implode(',');
```
is much better.

**Comment by DusanKasan** [comment]
I understand your use case, however I don't think that adding a new method that can be easily achieved by using `reduce`or composed by calling `interpose` and `toString` in sequence (which is how this would be implemented if we decided to add it, your implementation needs to traverse the itemse twice) would be best for the project. I try to keep the API surface minimal.

Also i think the solution provided by @issei-m is probably the most 'functional', as in this is how it would be done in a functional language.

So this PR won't be merged. But can you please expand on why the solutions we offered aren't acceptable for you?

**Comment by milous** [comment]
> your implementation needs to traverse the itemse twice

Good point. I missed it.

> I try to keep the API surface minimal.

Ok.

> But can you please expand on why the solutions we offered aren't acceptable for you?

Your solution is acceptable for me.
```php
Collection::from([1, 2, 3])
    ->interpose('a')
    ->values()
    ->toString();
```

Soulution
```php
Collection::from([1, 2, 3])->implode('a');
```
is more KISS for my view.

thx @DusanKasan @issei-m

**Comment by DusanKasan** [comment]
No need to call `values` in your last example :)

**Pull request closed without merging**
