### PR TITLE
Add missing semicolon in code examples in the docs

### PR DESCRIPTION
**Pull request by jdreesen**

### CODE REVIEW

**Review by issei-m — APPROVED** [review]
LGTM. Although CI task is failed it's not related to these changes and I'm [opening the PR](https://github.com/DusanKasan/Knapsack/pull/56) where I'm addressing it.

**Comment by DusanKasan** [comment]
Yeah, LGTM too, will have to fix the CI first.

**Comment by issei-m** [comment]
@jdreesen Could you rebase onto latest master branch where the CI error has gone?

**Comment by jdreesen** [comment]
Done. Everything's green now. Thx for solving the Scrutinizer issues :)

**Comment by DusanKasan** [comment]
LGTM thanks for the contribution.

**Pull request merged**
