### PR TITLE
Update some vulnerable dependencies

### PR DESCRIPTION
**Pull request by issei-m**
Some packages are claimed as vulnerable via the [Scrutinizer task](https://scrutinizer-ci.com/g/DusanKasan/Knapsack/inspections/2fafd618-59d9-4484-9336-5a99d9567d8f/issues/files/composer.lock?status=failed&conditionIds%5B0%5D=330583). So upgraded these packages. 
Btw I suppose it might be the time to drop PHP 5.6 support...

### CODE REVIEW

**Comment by issei-m** [comment]
CI task is now failed. OK, let me try to fix.

**Comment by DusanKasan** [comment]
I'll have a look at the scrutinizer errors today after work, it seems like an issue with test dependency versions. Probably Symfony components and/or PhpSpec.

Edit: And I'm also up for deprecating 5.6 support as its not supported from 2019-1-1.

**Comment by issei-m** [comment]
if I understood correctly, two vulnerable packages are:

- phpunit/phpunit
- squizlabs/php_codesniffer

And to fix that, I attempted upgraded these packages with dependencies for them, and that succeeded.
However, now, a new problem appears that [one of the upgraded packages is using reserved term `Resource` for HHVM](https://scrutinizer-ci.com/g/DusanKasan/Knapsack/inspections/1b35f23a-0a36-4284-aebd-a02e6755afdd). 
So I suppose we have two options to address this fact:

- Drop supporting HHVM from CI
  - This is not a huge problem because this problem should appear only on CI
  - Futhermore, famous libraries such as Symfony has already dropped it a few years ago
- Disable `Eval.EnableHipHopSyntax` HHVM option somehow
  - I found this way that might be able to fix it: https://github.com/facebook/hhvm/issues/1654 but I'm not sure how to realize it on Scrutinizer task

**Comment by DusanKasan** [comment]
@issei-m yes, I think it would be fine to drop the HHVM support now, since they will stop supporting PHP syntax officially anyway.

**Comment by issei-m** [comment]
Okay. I'll begin to drop HHVM from CI later (soon). Thanks for sharing your opinion 😉

**Comment by issei-m** [comment]
@DusanKasan I've done dropping HHVM, but CI is still failed. As you can see the Scrutinizer score has been reduced to less than 7.0 (the index specified in Scrutinizer config) before we knew it.
Apparently both of [CollectionSpec](https://scrutinizer-ci.com/g/DusanKasan/Knapsack/code-structure/master/class/spec%5CDusanKasan%5CKnapsack%5CCollectionSpec) and [CollectionTrait](https://scrutinizer-ci.com/g/DusanKasan/Knapsack/code-structure/master/class/DusanKasan%5CKnapsack%5CCollectionTrait) are marked as Fatal. So we should do at least either refactoring or tolerating them. What do you think?

**Comment by DusanKasan** [comment]
@issei-m I flagged the "issues" in CollectionSpec and CollectionTrait as false positives (which they were). But i am unable (or just don't know how) to re-run the inspections on the PR branch, could you try to trigger them, please?

If it won't help we could lower the threshold, but I would like to avoid that :)

**Comment by issei-m** [comment]
@DusanKasan Re-ran the task by made new some minor changes (I also cannot schedule the Scrutnizer task for permission problem)

Unfortunately, it seems problem hasn't gone. So could you confirm the filter config again?
https://scrutinizer-ci.com/docs/reviews/filtering_issues_and_false_positives

**Comment by DusanKasan** [comment]
The issue now can be fixed either by lowering the fail treshold to 6.8 or something or by excluding the /tests/* from quality checks. Both are fine by me by I am leaning towards excluding the tests. Thoughts?

**Comment by issei-m** [comment]
@DusanKasan Now, excluding all test files in favor of your latter recommendation 😉

**Comment by issei-m** [comment]
And now score has increased up to over 7 where we can merge it.
Thank you for your advise.

**Comment by DusanKasan** [comment]
Looks good, thanks for all the work @issei-m

**Pull request merged**
