### PR TITLE
Add a transpose function

### PR DESCRIPTION
**Pull request by petemcfarlane**
Hi, I would like to add a transpose function to a collection

``` php
// input
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
// output
[
    [1,4,7],
    [2,5,8],
    [3,6,9]
]
```

switching the row and column indexes. I have this PR, but I think the code could be improved and I need to update the README.md. 

Do you think this would be a useful function? Are there any suggestions you would have for testing edge cases?

Thanks

### CODE REVIEW

**Comment by DusanKasan** [comment]
Well, we could include it, but are there any real use cases? The form processing use case seems pretty far fetched to me.

For transpose implementation that works with arrays, you can check [this](https://github.com/DusanKasan/Knapsack/blob/master/tests/scenarios/CustomPassthroughFunctionTest.php). However, if we decide to include this, we should use this function:

``` php
function transpose($collection)
{
    return Collection::from(
        array_map(
            function (...$items) {
                return $items;
            },
            ...toArray(
                map(
                    $collection,
                    'DusanKasan\Knapsack\toArray'
                )
            )
        )
    );
}
```

**Comment by petemcfarlane** [comment]
Hmm ok, I see you've read the same [post as me](https://github.com/DusanKasan/Knapsack/pull/21)!
Yeah I don't have another good use for it yet so feel free to ignore it. Just thought it was quite cool and I liked this project, so thought I'd contribute it. That is a much better implementation too IMO.

**Comment by DusanKasan** [comment]
Well, transpose isn't easily composable from currently provided functions/methods, so we may benefit from including it into Knapsack. You can change the implementation in this pull request to what i proposed (or maybe you'll think of something better) and we can merge it into master.

So what needs to be done:
- change implementation
  - when collection items are of inconsistent length, the missing items are replaced by null (done by my proposed implementation)
  - when collection items are not collection, exception should be thrown (needs to be implemented)
- add readme
- add tests
  - consistent item length
  - inconsisten item length
  - some items are not collections

Just reply here if you feel up to it :)

**Comment by DusanKasan** [comment]
Better late than never :) I merged the PR and added the docs.

**Pull request merged**
